{
"grace": {"author_nick": "Maria Clara", "author_name": "Maria Clara", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"kristen": {"author_nick": "Lilian", "author_name": "Lilian", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"angie": {"author_nick": "Angelica V", "author_name": "Angelica V", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"courtney": {"author_nick": "Sthefani", "author_name": "Sthefani", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"samantha": {"author_nick": "Samantha", "author_name": "Samantha", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"alexa": {"author_nick": "Monica", "author_name": "Monica", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"amanda": {"author_nick": "Angelica Z", "author_name": "Angelica Z", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"libby": {"author_nick": "Livia", "author_name": "Livia", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"lisa": {"author_nick": "Duda", "author_name": "Duda", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"anastasia": {"author_nick": "Raquele", "author_name": "Raquele", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"callie": {"author_nick": "Marcelle", "author_name": "Marcelle", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"danae": {"author_nick": "Carlo", "author_name": "Carlo", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"roxanne": {"author_nick": "Priscila", "author_name": "Priscila", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"adda": {"author_nick": "Horty", "author_name": "Horty", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"sara": {"author_nick": "Marco", "author_name": "Marco", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"sarah": {"author_nick": "Mariana", "author_name": "Mariana", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"stacy": {"author_nick": "Ana Caroline", "author_name": "Ana Caroline", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"julia": {"author_nick": "Julia", "author_name": "Julia", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
"meredith": {"author_nick": "Rodrigo", "author_name": "Rodrigo", "author_email": "", "author_org": "LABASE", "author_site": "http://labase.superpython.net", "author_public": "on"},
